import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  development: [
    {
      type: 'category',
      label: '开发',
      collapsible: false,
      items: [
        {
          type: 'category',
          label: '结构',
          link: { type: 'generated-index' },
          items: [{ type: 'autogenerated', dirName: 'development/structures' }],
        },
        {
          type: 'category',
          label: 'JS插件',
          link: { id: 'development/js/README', type: 'doc' },
          items: [
            'development/js/serein',
            {
              type: 'category',
              label: '类',
              link: { type: 'generated-index' },
              items: [
                { type: 'autogenerated', dirName: 'development/js/classes' },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'API',
          link: { id: 'development/api/README', type: 'doc' },
          items: [
            'development/api/version',
            'development/api/sysInfo',
            {
              type: 'category',
              label: '设置',
              items: [
                'development/api/settings/get',
                'development/api/settings/set',
              ],
            },
            {
              type: 'category',
              label: '连接',
              items: ['development/api/network/info'],
            },
            {
              type: 'category',
              label: '服务器',
              items: [
                'development/api/servers/infos',
                'development/api/servers/info',
                'development/api/servers/create',
                'development/api/servers/edit',
                'development/api/servers/delete',
              ],
            },
          ],
        },
      ],
    },
  ],

  guidance: [
    {
      type: 'category',
      label: '指南',
      collapsible: false,
      items: ['guidance/index'],
    },
  ],

  tutorial: [
    {
      type: 'category',
      label: '教程',
      collapsible: false,
      items: ['index'],
    },
  ],
};

export default sidebars;
