import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import type { SidebarConfig } from '@docusaurus/plugin-content-docs/src/sidebars/types';

const development: SidebarConfig = [
  {
    type: 'category',
    label: '开发',
    collapsible: false,
    link: { type: 'doc', id: 'development/index' },
    items: [
      {
        type: 'category',
        label: '插件',
        link: { type: 'doc', id: 'development/plugins/index' },
        collapsible: false,
        items: [
          'development/plugins/net/index',
          {
            type: 'category',
            label: 'JavaScript',
            link: { id: 'development/plugins/js/index', type: 'doc' },
            items: [
              'development/plugins/js/app',
              'development/plugins/js/console',
              'development/plugins/js/plugins',
              'development/plugins/js/servers',
              'development/plugins/js/exports_imports',
              'development/plugins/js/net',
              {
                type: 'category',
                label: '结构',
                link: { type: 'generated-index' },
                items: [
                  {
                    type: 'autogenerated',
                    dirName: 'development/plugins/js/structures',
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        type: 'category',
        label: 'API',
        link: { id: 'development/api/index', type: 'doc' },
        items: [
          'development/api/root',
          {
            type: 'category',
            label: '连接',
            items: ['development/api/connection/info'],
          },
          {
            type: 'category',
            label: '硬件信息',
            link: { id: 'development/api/hardware/index', type: 'doc' },
            items: [
              'development/api/hardware/batteries',
              'development/api/hardware/bios',
              'development/api/hardware/cpus',
              'development/api/hardware/drives',
              'development/api/hardware/keyboards',
              'development/api/hardware/memory',
              'development/api/hardware/memory_status',
              'development/api/hardware/monitors',
              'development/api/hardware/motherboards',
              'development/api/hardware/mouses',
              'development/api/hardware/os',
              'development/api/hardware/printers',
              'development/api/hardware/soundDevices',
              'development/api/hardware/system',
            ],
          },
          {
            type: 'category',
            label: '服务器',
            items: [
              'development/api/servers/infos',
              'development/api/servers/info',
              'development/api/servers/create',
              'development/api/servers/edit',
              'development/api/servers/delete',
              'development/api/servers/start',
              'development/api/servers/stop',
              'development/api/servers/terminate',
              'development/api/servers/input_get',
              'development/api/servers/input_post',
            ],
          },
          {
            type: 'category',
            label: '设置',
            items: [
              'development/api/setting/get',
              'development/api/setting/update',
            ],
          },
        ],
      },
      {
        type: 'category',
        label: 'WebSocket',
        link: { type: 'doc', id: 'development/ws/index' },
        items: ['development/ws/listen'],
      },
    ],
  },
];

const guidance: SidebarConfig = [
  'index',
  {
    type: 'category',
    label: '指南',
    collapsible: false,
    items: [
      'guidance/command',
      'guidance/variables',
      'guidance/servers',
      'guidance/plugins',
    ],
  },
];

const tutorial: SidebarConfig = [
  {
    type: 'category',
    label: '教程',
    collapsible: false,
    link: { type: 'doc', id: 'tutorial/index' },
    items: [
      {
        type: 'category',
        label: '入门',
        collapsible: false,
        link: { type: 'generated-index' },
        items: [
          'tutorial/rookie/get_started',
          'tutorial/rookie/choose',
          'tutorial/rookie/add_server',
        ],
      },
      {
        type: 'category',
        label: '进阶',
        collapsible: false,
        link: { type: 'generated-index' },
        items: ['tutorial/advanced/commandline_args'],
      },
    ],
  },
];

const sidebars: SidebarsConfig = {
  development,
  guidance,
  tutorial,
};

export default sidebars;
